# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ethical-strategy-app"
client_id = "f4a99db3d71a2094360301ae11c68734"
application_url = "https://5e2b-2001-ee0-8206-c0cd-2927-8e8-13fc-c160.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://5e2b-2001-ee0-8206-c0cd-2927-8e8-13fc-c160.ngrok-free.app/auth/callback",
  "https://5e2b-2001-ee0-8206-c0cd-2927-8e8-13fc-c160.ngrok-free.app/auth/shopify/callback",
  "https://5e2b-2001-ee0-8206-c0cd-2927-8e8-13fc-c160.ngrok-free.app/api/auth/callback",
  "https://5e2b-2001-ee0-8206-c0cd-2927-8e8-13fc-c160.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f90ac0b9.myshopify.com"
