# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "nn276-app"
client_id = "ae0b7f5165a8f118076bce61906af8ef"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-f90ac0b9.myshopify.com"
